# Generated by Django 4.1.5 on 2023-02-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(default='', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('qty', models.FloatField(default=0)),
                ('image', models.CharField(max_length=300)),
                ('image2', models.CharField(default='https://www.jta.org/wp-content/uploads/2017/06/bubble-gum-960x600.jpg', max_length=300)),
            ],
        ),
    ]
