# Generated by Django 4.1.5 on 2023-01-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.CharField(default='https://www.jta.org/wp-content/uploads/2017/06/bubble-gum-960x600.jpg', max_length=300),
        ),
    ]
