# Generated by Django 4.1.5 on 2023-02-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
